### ISSUE TITLE
ShopifyAPI::Shop.current raises undefined method `construct_api_path' for nil:NilClass

### ISSUE THREAD

**Issue by anark** [Shopify/shopify_api#614]
After upgrading to v7.0.2 from 5.2.0 I get the error of
```undefined method `construct_api_path' for nil:NilClass```

When calling
```
    ShopifyAPI::Session.temp(domain: url, token: token, api_version: '2019-07') do
      ShopifyAPI::Shop.current
    end
```

**Comment by nwtn** [comment]
hi anark. are you using 7.0.0, 7.0.1, or 7.0.2?

**Comment by anark** [comment]
7.0.2

**Comment by anark** [comment]
> hi anark. are you using 7.0.0, 7.0.1, or 7.0.2?

7.0.2

**Comment by nwtn** [comment]
In the code you shared, you’re creating a temp session. At the point where you run this, have you already created a non-temp session? If not, I think that’s the problem.

Creating a temp session assumes that you already have a non-temp original session:

* https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L23-L27
* https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L29-L38
* https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L79-L84

I suspect your error is happening when `with_session` calls `extract_current_session` to get the original session. `extract_current_session` grabs `ShopifyAPI::Base.api_version`; by default, if you haven’t already created a session, this will be a `ShopifyAPI::ApiVersion::NullVersion`, which will result in `construct_api_path` failing for it.

In this case the solution would be for you to use `Session.new` instead of `Session.temp`, or to only run `Session.temp` after you’ve instantiated a non-temp session.

**Comment by anark** [comment]
In previous versions the temp session never required an original session and the point of temp session was to execute calls without having to create a normal session and to close the temp session after executing those calls.

If you have to create a normal session first what would be the point of temp session?

**Comment by marschattha** [comment]
> If you have to create a normal session first what would be the point of temp session?

True, this is also breaking Shopify app gem's with_shopify_session function as well.

**Comment by nwtn** [comment]
Thanks for the additional context. I spent some more time looking at this this morning and have a couple updates:

* The explanation I posted above isn’t quite right, as I was looking at/pointing to code on `master`, not `7.0.2`. That said, this has exposed a bug in master with `ShopifyAPI::ApiVersion::NullVersion` not being properly coerce-able :)

* In 7.0.2, in a fresh Rails app, I am _not_ currently able to recreate the problem as described. When I step through the code I can see that https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L129-L131 correctly assigns coerces the version for the temp session and correctly `nil` to `@api_version` for the original session. I’m not able to get the `undefined method `construct_api_path' for nil:NilClass` error while doing a call inside the `Session.temp`

> If you have to create a normal session first what would be the point of temp session?

The temp session is useful if you need to, e.g., query a specific endpoint with a different version than you’re using in your normal session. That said, you’re right that the temp session creation/execution shouldn’t be failing in this way — an original session with nil values for version, etc., shouldn’t cause an error like this.

@anark since I can’t reproduce with the code you’ve posted, would you be able to share either a stack trace or more code? Are there any API calls you’re making outside of the session block you posted above?

**Comment by anark** [comment]
@nwtn Thanks for the help.

I think the issue was actually that ShopifyAPI::Base.clear_session was clearing ShopifyAPI::Base.api_version.  I had setup Shopify::Base.api version in an initializer and expected it to persist not realizing that clear_session would wipe this setting.

It would be nice in the future if there was a way to set a default api version in an application instead of having to specify it for each call.

**Comment by marschattha** [comment]
>  I had setup Shopify::Base.api version in an initializer and expected it to persist not realizing that clear_session would wipe this setting.

What? I'm also setting it in initializer as a work around. It will get cleared? Found any other work around?

**Comment by isaacbowen** [comment]
All of our API requests happen in the context of a particular shop record, so it made sense to solve this in our existing Shop#session method. It currently resembles this:

```rb
class Shop
  def session api_version: ShopifyAPI::ApiVersion::NullVersion, &block
    # firstly, make sure that we haven't lost ShopifyAPI::Base.api_version,
    # because ShopifyAPI::Session::extract_current_session will complain if
    # it's nil, and that happens right here:
    # https://github.com/Shopify/shopify_app/blob/84184b/lib/shopify_app/controller_concerns/login_protection.rb#L25
    if _is_null_version?(ShopifyAPI::Base.api_version)
      ShopifyAPI::Base.api_version = ANOTHER_CONST_WHERE_WE_KEEP_OUR_DEFAULT_VERSION
    end

    # onward. make sure we're using an actual version for this here session.
    if _is_null_version?(api_version)
      api_version = ShopifyAPI::Base.api_version
    end

    if block_given?
      ShopifyAPI::Session.temp(
        domain: shopify_domain,
        token: shopify_token,
        api_version: api_version,
        &block
      )
    else
      ShopifyAPI::Session.new(
        domain: shopify_domain,
        token: shopify_token,
        api_version: api_version,
      )
    end
  end

  def _is_null_version? thing
    thing.nil? or thing == ShopifyAPI::ApiVersion::NullVersion
  end
end
```

**Comment by AfolabiOlaoluwa** [comment]
How can I get the current shop from another model? When I do `ShopifyAPI::Shop.current`, all I get is `ShopifyAPI::ApiVersion::ApiVersionNotSetError: You must set ShopifyAPI::Base.api_version before making a request.`. I am using Shopify App Gem and cant proceed to make this work despite `api_version` is set in the initializer
