### ISSUE TITLE
activeresource 5.1.0 seems to breaking this gem

### ISSUE THREAD

**Issue by kapso** [Shopify/shopify_api#504]
```
NoMethodError: undefined method `path' for nil:NilClass (Most recent call first)
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 701 in prefix
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 711 in prefix_source
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1126 in prefix_parameters
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1141 in block in split_options
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1139 in each
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1139 in split_options
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1661 in split_options
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1439 in load
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1181 in initialize
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1462 in new
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1462 in block in load
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1447 in each
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1447 in load
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1181 in initialize
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1462 in new
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1462 in block in load
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1447 in each
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1447 in load
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1181 in initialize
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1108 in new
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1108 in instantiate_record
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 1097 in find_single
File /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb line 984 in find
```

**Comment by 0ptimusrhyme** [comment]
Can you provide a little more info? Using activeresource 5.1.0 on shopify_api 5.2.0 yields no issues for me. Replication steps always appreciated.

**Comment by kapso** [comment]
This was during - `ShopifyAPI::Order.find(id)`

**Comment by 0ptimusrhyme** [comment]
I cannot replicate by following that pattern. Can you provide more information? Such as what shopify_api version, a script demonstrating the issue, etc?

**Comment by kapso** [comment]
Hmm I am not sure what version of the Shopify API this gem uses. That info is abstracted out by this gem, no? Thats the whole purpose of this gem.

All I know is the Shopify requests like `ShopifyAPI::Order.find(id)` started failing after upgrading `activeresource`  to `5.1.0`.

**Comment by 0ptimusrhyme** [comment]
To be clear, I'm asking about the gem version. This is visible in your environment or with the `ShopifyAPI::VERSION` constant during runtime.

**Comment by kapso** [comment]
Ah sorry, I am using the following Gem

```
shopify_app (8.3.2)
shopify_api (5.2.0)
```

**Comment by 0ptimusrhyme** [comment]
Since I cannot replicate with the same `shopify_api`/`activeresource`/`shopify_app` gem versions, would you mind sharing a script that can be used to reliably replicate the issue? For example:

```rb
# Assuming shopify_api version 5.2.0 and activeresource version 5.1.0,
# and shopify_app version 8.3.2
session = ShopifyAPI::Session.new('shop.myshopify.com', access_token)
ShopifyAPI::Base.activate_session(session)

ShopifyAPI::Order.find(order_id)
```

**Comment by kapso** [comment]
Unfortunately cannot share the access token and store URL.

Do you think this could be a store specific issue?

**Comment by 0ptimusrhyme** [comment]
I don't believe it's a store specific issue. You don't have to share the access token or shop URL if that's the case, and it's worth trying out. Just share a snippet like I showed in my last comment with dummy values.

The error specifically seems to be indicating that `site` is `nil` and therefore `path` is not defined [here](https://github.com/rails/activeresource/blob/master/lib/active_resource/base.rb#L702).

`site` is set on `ShopifyApp::Base.activate_session` [here](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/base.rb#L55). `activate_session` pulls from the `Session`'s `site` [here](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L108) which is set on `ShopifyAPI::Session.new`'s `url` property [here](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L71).

The above indicates that perhaps you're not instantiating a session properly? Anyway, looking forward to an example (with redacted sensitive information).

**Comment by dashmetriks** [comment]
I am also having an issue with the finding an order.  I get output here https://doofdoof4.myshopify.com/admin/orders/569584451687.json, but get 
ShopifyAPI::Order.find(569584451687)
ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found.
from /home/ec2-user/.rvm/gems/ruby-2.3.3/gems/activeresource-5.1.0/lib/active_resource/connection.rb:147:in `handle_response'

I am not sure if it is a date issue since 569584451687 has order date of  2018-08-16, because ShopifyAPI::Order.find(644479320167) of a recent order does give order data.

gem 'rails', '~> 5.1.2'
ruby '2.3.3'
gem 'shopify_app', '~> 7.2.0'
gem 'shopify_api', '~> 5.2'

gem list
activerecord (5.1.6, 5.1.5, 5.1.4, 5.1.2, 5.1.0)
activeresource (5.1.0, 5.0.0)
activesupport (5.1.6, 5.1.5, 5.1.4, 5.1.2, 5.1.0)

**Comment by 0ptimusrhyme** [comment]
@dashmetriks your issue is unrelated to the one being discussed here.

If you don't have the `read_all_orders` access scope, you will have to request access to it under your specific app's area in your partner dashboard. Once you are given access to the scope, you can request `read_all_orders` during your installs, and you'll be able to see orders older than 60 days through the API.

See this announcement: https://ecommerce.shopify.com/c/api-announcements/t/action-required-apps-require-shopify-approval-to-read-orders-older-than-60-days-523231

**Comment by kapso** [comment]
@0ptimusrhyme But the same code (live production Shopify app) works fine with `activeresource (5.0.0)`

Here's the code, `find_shopify_order` fails with the above error when `activeresource (5.1.0)` is used

```ruby
def find_shopify_order(id)
  shopify_request(ShopifyAPI::Order, :find, id)
end

def shopify_request(klass, method, *params)
  with_shopify_session { klass.send(method, *params) }
end

def with_shopify_session(&block)
  ShopifyAPI::Session.temp(shopify_store_domain, shopify_token, &block)
end
```

**Comment by kapso** [comment]
@0ptimusrhyme please let me know if you need any other data points. Thanks!

**Comment by sheppyh** [comment]
I also have this issue when deploying to Heroku, but not locally....

**Comment by kapso** [comment]
BTW this issue got fixed for me. Only difference since I opened this issue was the `shopify_*` gems upgrade.

```
shopify_app (8.5.1)
shopify_api (5.2.4)
```

**Comment by sheppyh** [comment]
Just upgraded, issue still present:
```
remote:        Using shopify_api 5.2.4
remote:        Fetching shopify_app 8.5.1

```
`2019-03-01T23:43:09.043255+00:00 app[web.1]: /app/vendor/bundle/ruby/2.5.0/gems/activeresource-5.1.0/lib/active_resource/base.rb:701:in `prefix': undefined method `path' for nil:NilClass (NoMethodError)
`
Called by 
`ShopifyAPI::Product.find(:all, params: { limit: 250 }).each do |product|`

**Comment by jheathco** [comment]
Can confirm same issue with Heroku (but not locally)

**Comment by jheathco** [comment]
Make sure your ShopifyAPI::Base.site is set in production as well as locally.

**Comment by alegrria** [comment]
Started having the same issue.
`ShopifyAPI::Order.new(order_attributes)` and `ShopifyAPI::Order.find(order_id)` give `NoMethodError Exception: undefined method `path' for nil:NilClass`
```
activeresource (5.1.0)
shopify_api (5.2.4)
shopify_app (8.3.2)
```

**Comment by mbbertino** [comment]
I started having the issue a couple months back and then it disappeared. Just a few hours ago I was getting 5,000+ of these errors. All of which seemed to be coming from an ActiveResource 5.1.0 that was from a `ShopifyAPI::Order.find({{shopify_order.id}})`. 

I hadn't upgraded anything and I was on
- `5.2.0` of `shopify_api`
- `5.1.0` of  `activeresource`

Just to see if it made a difference I upgraded to `shopify_api` `7.1.0` and re-ran the failed webhook events. All of the re-ran successfully. 

The version bump of `shopify_api` did not result in a bump in the `activeresource` however so I'm not sure what actually fixed it. But the problems stopped once I upgraded from what I can tell. 

Hopefully, this helps someone else.

**Comment by mbbertino** [comment]
I wanted to follow-up on this, I just got another small "flood" of these errors. This leads me to believe that the gem upgrade did in fact not solve the issue. 

The only thing I can think of was that there was a recent deploy right before. Could that for any reason have an impact on this?

I'm happy to help work on this or dig in further I'm just not sure what direction I should 😃

**Comment by tanema** [comment]
The last time I went digging for this, it seems like a load order issue. I cannot remember the specifics exactly but I know there is a gotchya in Rails for constant loading and setting values on those constants since they will not be reloaded. It may be the order that your initializers run. Are you doing anything else with active resource in your application?

**Comment by mbbertino** [comment]
@tanema The only time my application reference `ActiveResource` is when handling errors.  I have it a few places in my background jobs (tech in the POROs they call)

For example
``` ruby 
rescue ActiveResource::ClientError => e
      raise e unless e.response.code.to_s == '429' 
```

Otherwise, I'm not monkey patching or doing anything other than standard rails stuff.

**Comment by tanema** [comment]
The error is the same as stated in 2018


> The error specifically seems to be indicating that `site` is `nil` and therefore `path` is not defined [here](https://github.com/rails/activeresource/blob/master/lib/active_resource/base.rb#L702).
> 
> `site` is set on `ShopifyApp::Base.activate_session` [here](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/base.rb#L55). `activate_session` pulls from the `Session`'s `site` [here](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L108) which is set on `ShopifyAPI::Session.new`'s `url` property [here](https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L71).
> 
> The above indicates that perhaps you're not instantiating a session properly? 

Where is the error stemming from in your code? Is it on startup? In your background job? Is it possible that you have some codepaths that might miss the session activation?

**Comment by mbbertino** [comment]
It is only happening in a background job which handles order event Webhooks. In our case create, update, delete events.

At this point we handle 7k plus order Webhooks an hour but this error is not happening on all of them.

That said anything is possible so I’ll double check the pathing in my worker and report back.



Matt Bertino - Founder, PostPilot.com

**Comment by marisveide** [comment]
Yes, we too have the same issue popping up randomly - it loses the `self.site` value - it suddenly becomes `nil` here:

```
Error: NoMethodError - undefined method `path' for nil:NilClass
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:701:in `prefix'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:711:in `prefix_source'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1126:in `prefix_parameters'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1141:in `block in split_options'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1139:in `each'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1139:in `split_options'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1661:in `split_options'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1439:in `load'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1181:in `initialize'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1462:in `new'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1462:in `block in load'
```

We suspect it might be some multi-threading issue, but cannot reproduce at will - only appears seemingly randomly.

<img width="893" alt="Screenshot 2020-10-07 at 19 43 57" src="https://user-images.githubusercontent.com/17713131/95361499-7c377e80-08d5-11eb-9630-acb33f5f053c.png">

**Comment by mbbertino** [comment]
@marisveide we came to the same conclusion. Seems to mostly happen on `ShopifyAPI::Order` and I do believe this started happening when we moved to a multi-threaded env. 

Also, we hadn't seen this error since Feb until about 2 weeks ago and it randomly came back 😞 That said I did some more digging around this and here's what I came up with: 

In our app every time we need to activate a Session we do it from a single class:

``` ruby
class ShopifyApiGateway
  def self.activate(store)
    ShopifyAPI::Session.setup(
      api_key: 'SHOPIFY_API_KEY',
      secret: 'SHOPIFY_SHARED_SECRET'
    )
    session = ShopifyAPI::Session.new(
      domain: store.domain,
      token: store.token,
      api_version: 'VERSION'
    )
    ShopifyAPI::Base.activate_session(session)
  end
end
```

This allows us invocation like: 
``` ruby
def initialize(id)
  @store = ShopifyStore.find(id)
  ShopifyApiGateway.activate(@store)
end
```

Now when I'm looking in where `site.path` get's define here:
https://github.com/rails/activeresource/blob/v5.1.0/lib/active_resource/base.rb#L701 

Which to me it looks like it's getting set at the class level. So in our particular case I believe that would fall to the `ShopifyAPI::Base` here:
https://github.com/rails/activeresource/blob/v5.1.0/lib/active_resource/base.rb#L444

When I dig further into the backtrace I see that `activate_session` looks like: 
``` ruby 
def activate_session(session)
  raise InvalidSessionError.new("Session cannot be nil") if session.nil?
  self.site = session.site
  self.headers.merge!('X-Shopify-Access-Token' => session.token)
  self.api_version = session.api_version
end
```

This sets the class `site` and from the site on the session. Which is interesting because that class has a method `site` that returns a string. https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/session.rb#L130

``` ruby 
def site
  "https://#{domain}"
end
```

Which is being fed in my case from the initial class I set up. 

This is unfortunately where I got stumped. Not sure where to go from here. 

``` ruby
session = ShopifyAPI::Session.new(
  domain: store.domain,
  token: store.token,
  api_version: 'VERSION'
)
```

Anyone have thoughts?

**Comment by marisveide** [comment]
Hey, @mbbertino !

Thanks so much for digging - together there is a higher chance to find the root cause for this.

## Some more facts which might help maybe:
* Since 2020-08-01 we had 103 jobs which have hit this exact issue. Some of them for just one request, some more than 1300 requests, and also everything in between.
* Since 2020-08-01 those issues were appearing almost daily, with the biggest "ok" period of `2020-08-17 - 2020-08-20` (4 days of not having this issue).
* Out of those 103 jobs - only 2 were Customers, all the other 101 are Orders.
* All of the jobs which had this issue, were multi-threaded. We also have in principle single-threaded jobs, but those didn't have this issue.

## Zooming into the latest one which had this error:

* Threads: `5`
* Using pagination method: `since_id`

```
Error: NoMethodError - undefined method `path' for nil:NilClass

/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:701:in `prefix'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:711:in `prefix_source'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1126:in `prefix_parameters'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1141:in `block in split_options'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1139:in `each'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1139:in `split_options'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1661:in `split_options'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1439:in `load'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1181:in `initialize'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1462:in `new'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1462:in `block in load'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1447:in `each'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1447:in `load'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1181:in `initialize'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1462:in `new'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1462:in `block in load'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1447:in `each'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1447:in `load'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1181:in `initialize'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1108:in `new'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1108:in `instantiate_record'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1104:in `block in instantiate_collection'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/collection.rb:70:in `block in collect!'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/collection.rb:10:in `each'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/collection.rb:10:in `each'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/collection.rb:70:in `collect!'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1104:in `instantiate_collection'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1073:in `find_every'
/var/app/current/app/lib/extensions/shopify_api/resources/base.rb:26:in `find_every'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:974:in `find'
/var/app/current/vendor/bundle/ruby/2.7.0/gems/activeresource-5.1.1/lib/active_resource/base.rb:1006:in `all'
```

That was a query to find Orders by Name:
Calling the API call like this:

```ruby
ShopifyAPI::Order.all(params: {"name":"name123","status":"any","financial_status":"any","fulfillment_status":"any","since_id":0,"limit":250})
```

That happened within a few first requests, but then further that same thread just "healed" and continued working ok.

It looks like for a nano-moment the ShopifyAPI::Base has the `site` attribute as `nil`, and then since it's a Singleton (class-level attribute), then some other thread "fixes" it, and so it continues fine.
Typical race-condition.

But so far all our attempts to replicate that at will, are still unsuccessful.

We have added some additional logging in those places - to try and catch the moment who maybe sets it to nil, or passes nil session:

For this method:
`active_resource/base.rb`
```ruby
      # Sets the URI of the REST resources to map for this class to the value in the +site+ argument.
      # The site variable is required for Active Resource's mapping to work.
      def site=(site)
        self._connection = nil
        if site.nil?
          self._site = nil
        else
          self._site = create_site_uri_from(site)
          self._user = URI.parser.unescape(_site.user) if _site.user
          self._password = URI.parser.unescape(_site.password) if _site.password
        end
      end
```

And for this method:
`shopify_api/resources/base.rb`
```ruby
      def activate_session(session)
        raise InvalidSessionError.new("Session cannot be nil") if session.nil?
        self.site = session.site
        self.headers.merge!('X-Shopify-Access-Token' => session.token)
        self.api_version = session.api_version
      end
```

Let's see the next time we will get it as nil, we should see the stack trace - who caused it.
🤞

**Comment by marisveide** [comment]
## Hypothesis of what's causing it
1. Something sets the `Base::site` to `nil`. **=> monitoring this now in live**
2. Something initializes `Base::activate_session` with session that has no `site` in it. **=> monitoring this now in live**
3. When getting the response from API, the `ShopifyAPI::Order` class doesn't have the `site` class-variable initialized. There might be none of the Session variables initialized. **=> need to find a way to check/prove/disprove this**
4. Deployment of the new version might cause the Class variables to get "reset"/lost. **=> checked that there is no time correlation between the deploy and that exception.**

**Comment by marisveide** [comment]
> ## Hypotheses of what's causing it
> 1. 🚫 Something sets the `Base::site` to `nil`. **=> it's not being set to nil, it's just nil when it's read.**
> 2. 🚫 Something initializes `Base::activate_session` with session that has no `site` in it. **=> session is always set with the correct values**
> 3. ⏳ When getting the response from API, the `ShopifyAPI::Order` class doesn't have the `site` class-variable initialized. There might be none of the Session variables initialized. **=> testing this live now**
> 4. 🚫 Deployment of the new version might cause the Class variables to get "reset"/lost. **=> checked that there is no time correlation between the deploy and that exception.**

ok, so our experiment shows that when it gets the `Base::site` as `nil` - it's not being set to `nil`, it just is nil.
So the conclusion is that it's not initialized at the moment when something reads it.

We found this place very suspicious which creates a new `resource` by setting the class constant:

`ActiveResource::Base#create_resource_for`
```ruby
      # Create and return a class definition for a resource inside the current resource
      def create_resource_for(resource_name)
        resource = self.class.const_set(resource_name, Class.new(ActiveResource::Base))
        resource.prefix = self.class.prefix
        resource.site   = self.class.site
        resource
      end
```

Theoretically, this place might not be thread-safe - many threads can call the same place and change the class variable that's in the `resource_name`.

So we have made an extension that wraps this call in a Mutex.
Let's see if that helps. 🤞

**Comment by andyw8** [comment]
@marisveide Thank you for you ongoing investigating and reporting on this 👍

**Comment by marisveide** [comment]
Hi, all!

We with @andrisbriedis believe we have found a solution! Actually, all the credit goes to @andrisbriedis for noticing this now "obvious" flaw in the logic!

Look, there is a problem with this method:
`ActiveResource::Base#create_resource_for`
```ruby
      # Create and return a class definition for a resource inside the current resource
      def create_resource_for(resource_name)
        resource = self.class.const_set(resource_name, Class.new(ActiveResource::Base))
        resource.prefix = self.class.prefix
        resource.site   = self.class.site
        resource
      end
```

## The flow in a multi-threaded environment, where we definitely get the race condition:
1. It creates the `resource` variable with a new Class `ActiveResource::Base` as a value, and stores it in the global constant of `resource_name`.
2. Then from another thread someone reads the value from the same constant `resource_name`. And gets the empty class with no prefix and site attributes. So it crashes with `site` being nil when read from that global constant.
3. It sets the `prefix` and `site` attributes.

## The correct way to work with this should be:
1. Create a variable.
2. Set the `prefix` and `site` attributes.
3. Store in a global constant of the `resource_name` variable.

Code that we have overwritten on our side, but which might be put in the gem if we make a pull request:
`ActiveResource::Base#create_resource_for`
```ruby
    def create_resource_for(resource_name)
      resource = Class.new(ActiveResource::Base)
      resource.prefix = self.class.prefix
      resource.site = self.class.site
      self.class.const_set(resource_name, resource)

      resource
    end
```

It's like with magic - it's a mystery while you don't see how it's done. As soon as you see it, you cannot unsee it. :)

Any thoughts?

**Comment by tanema** [comment]
Wow! @marisveide and @andrisbriedis what a great find! I would recommend copy/pasting what you have here into your issue on activeresource. I will check in with our rails team to see if we have anyone that can review that PR.

**Comment by marisveide** [comment]
> Wow! @marisveide and @andrisbriedis what a great find! I would recommend copy/pasting what you have here into your issue on activeresource. I will check in with our rails team to see if we have anyone that can review that PR.

Thanks, @tanema !
I see that we didn't have the issue on ActiveResource gem.
I have made a pull request there, and referenced this issue - I hope that should be sufficient for those who will do the review.

**Comment by mbbertino** [comment]
@marisveide and @andrisbriedis way to keep digging here 💪 Great catch!
